require:
  - rubocop-rake
  - rubocop-minitest

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Gemspec/DevelopmentDependencies:
  Enabled: false

Layout/LineLength:
  Max: 120

# Metrics/AbcSize:
#   Max: 40

Metrics/BlockLength:
  Exclude:
    - another-ldap-proxy.gemspec
    - test/**/*.rb

Metrics/ClassLength:
  Exclude:
    - test/**/*.rb

Metrics/MethodLength:
  Max: 25
  Exclude:
    - test/**/*.rb

# Metrics/ParameterLists:
#   Exclude: []

Style/Documentation:
  Enabled: false
