#!/usr/bin/env ruby

require 'gli'

require 'another/ldap/proxy'

class Cli
  extend GLI::App

  program_desc 'Another::Ldap::Proxy CLI'

  version Another::Ldap::Proxy::VERSION

  desc 'Start the proxy'
  command :start do |c|
    c.desc 'Configuration file (YAML)'
    c.default_value "./proxy.yml"
    c.arg_name 'proxy.yml'
    c.flag [:c, :config], required: true

    c.action do |global_options, options, args|
      action_options = global_options.update(options)

      conf = Another::Ldap::Proxy::Conf.from_file(action_options[:config])
      Another::Ldap::Proxy::Server.run(conf: conf)
    end
  end

  default_command :start
end

exit Cli.run(ARGV)
